"""Command definitions for the address book application."""

from enum import StrEnum


class Command(StrEnum):
    """Enumeration of all available commands in the application."""
    ADD_CONTACT = "add"
    UPDATE_CONTACT = "change"
    SHOW_CONTACT = "phone"
    SHOW_ALL_CONTACTS = "all"
    SEARCH_CONTACTS = "search"
    SET_BIRTHDAY = "set-birthday"
    SHOW_BIRTHDAY = "show-birthday"
    DELETE_BIRTHDAY = "delete-birthday"
    SHOW_UPCOMING_BIRTHDAYS = "birthdays"
    DELETE_CONTACT = "delete"
    SET_EMAIL = "set-email"
    DELETE_EMAIL = "delete-email"
    SHOW_EMAIL = "show-email"
    SET_ADDRESS = "set-address"
    DELETE_ADDRESS = "delete-address"
    SHOW_ADDRESS = "show-address"
    HELLO = "hello"
    HELP = "help"
    HELP_ALT = "?"
    EXIT_1 = "exit"
    EXIT_2 = "close"
    ADD_NOTE = "add-note"
    LIST_NOTES = "list-notes"
    SEARCH_NOTES = "search-notes"
    EDIT_NOTE = "edit-note"
    DELETE_NOTE = "delete-note"
    SEARCH_TAGS = "search-tags"
    STATS = "stats"
