name: Python CI with Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8 pytest pytest-cov

      - name: Lint code with flake8
        run: |
          flake8 . --max-line-length=100 --ignore=E501,W503

      - name: Run tests with pytest and coverage
        run: |
          pytest --cov=. --cov-report=term-missing -v

      - name: Save coverage report
        if: always()
        run: |
          pytest --cov=. --cov-report=xml
        continue-on-error: true

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: coverage.xml
